# Generated by Django 4.1.3 on 2023-02-25 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoGanttChartApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='id',
        ),
        migrations.AlterField(
            model_name='categories',
            name='CATEGORY_ID',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
