# Generated by Django 4.1.3 on 2023-02-25 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoGanttChartApp', '0002_remove_categories_id_alter_categories_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='CATEGORY_NAME',
            field=models.CharField(max_length=20),
        ),
    ]
